# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 

exclude: ["README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : 老王博客
tagline: 努力做一个真实的人
author :
  name : Denis Wang
  email : wangyg.personal@gmail.com
  github : wangyingang
  twitter : wangyg
  feedburner : feedname

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://wangyingang.github.com

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html

comments:
  provider: disqus
  disqus:
    short_name: wygblog
